# Generated by Django 5.2.13 on 2026-04-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNMODERATED', 'Unmoderated'), ('MODERATION', 'Moderation'), ('MODERATED', 'Moderated'), ('REJECTED', 'Rejected')], default='UNMODERATED', max_length=32),
        ),
    ]
