# Generated by Django 5.2.13 on 2026-04-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_category_uuid_and_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ON_MODERATION", "On moderation"),
                    ("MODERATED", "Moderated"),
                    ("BLOCKED", "Blocked"),
                ],
                default="CREATED",
                max_length=32,
            ),
        ),
    ]
