# Generated by Django 5.2.13 on 2026-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_seller_and_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sku",
            name="discount",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sku",
            name="image",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
