# Generated by Django 5.2 — SKU: quantity + characteristics

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sku",
            name="characteristics",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
