# Generated by Django 5.2.13 on 2026-04-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevokedRefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.UUIDField(unique=True)),
                ("revoked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revoked_refresh_tokens",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={"ordering": ["-revoked_at"]},
        ),
    ]
