"""Коды ошибок approve-flow."""

TICKET_WRONG_STATUS = "TICKET_WRONG_STATUS"
TICKET_NOT_ASSIGNED = "TICKET_NOT_ASSIGNED"
PRODUCT_EDITED_DURING_REVIEW = "PRODUCT_EDITED_DURING_REVIEW"
NO_SKU = "NO_SKU"
