"""Коды ошибок ticket-flow."""

TICKET_WRONG_STATUS = "TICKET_WRONG_STATUS"
TICKET_NOT_ASSIGNED = "TICKET_NOT_ASSIGNED"
TICKET_TERMINAL = "TICKET_TERMINAL"
PRODUCT_EDITED_DURING_REVIEW = "PRODUCT_EDITED_DURING_REVIEW"
NO_SKU = "NO_SKU"
INVALID_BLOCKING_REASON = "INVALID_BLOCKING_REASON"
